In [2]:
import torch

In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [12]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.shape

torch.Size([2])

In [17]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
MATRIX = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
]])

MATRIX

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
MATRIX.shape

torch.Size([1, 3, 3])

In [26]:
MATRIX.ndim

3

In [31]:
torch.rand(3, 3)

tensor([[0.4592, 0.0140, 0.8731],
        [0.7871, 0.5539, 0.9671],
        [0.5938, 0.8681, 0.3839]])

In [34]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [41]:
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [52]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # convert to zeroes
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None,
    requires_grad=False,
)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.ndim, float_32_tensor.device

(torch.Size([3]), torch.float32, 1, device(type='cpu'))

In [64]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16,
)

float_16_tensor.dtype

torch.float16

In [70]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f'Shape of tensors: {some_tensor.shape}')
print(f'Data type of tensors: {some_tensor.dtype}')
print(f'Number of dimensions of tensors: {some_tensor.ndim}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.0165, 0.0630, 0.0477, 0.8601],
        [0.8062, 0.8512, 0.5590, 0.3795],
        [0.4799, 0.5563, 0.0380, 0.5135]])
Shape of tensors: torch.Size([3, 4])
Data type of tensors: torch.float32
Number of dimensions of tensors: 2
Device tensor is stored on: cpu


In [79]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [80]:
tensor * 10

tensor([10, 20, 30])

In [81]:
tensor

tensor([1, 2, 3])

In [82]:
tensor = tensor -10
tensor

tensor([-9, -8, -7])

In [83]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [84]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [85]:
tensor

tensor([1, 2, 3])

In [87]:
print(tensor, '*', tensor)
print('Equals: ', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [89]:
torch.matmul(input=tensor, other=tensor)

tensor(14)

In [91]:
import torch

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [92]:
tensor.shape

torch.Size([3])

In [93]:
tensor  * tensor

tensor([1, 4, 9])

In [97]:
print(torch.matmul(tensor, tensor))
print(tensor * tensor)
print(tensor @ tensor)

tensor(14)
tensor([1, 4, 9])
tensor(14)


In [98]:
%%time
value = 0
for i in range((len(tensor))):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 4 ms


tensor(14)

In [102]:
%%time
torch.matmul(tensor, torch.tensor([4, 8, 8]))

CPU times: total: 0 ns
Wall time: 0 ns


tensor(44)

In [105]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6],
], dtype=torch.float32)

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [110]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [111]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [116]:
print(F'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} * {tensor_B.T.shape}')
print('Output\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3])
Output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [117]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [122]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=3)

X = tensor_A
output = linear(x)
X

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [124]:
print(f'Input shape: {X.shape}\n')
print(f'Output: {output}\nOutput shape: {output.shape}\n')

Input shape: torch.Size([3, 2])

Output: tensor([[1.3702, 1.5487, 0.7538],
        [3.6252, 2.5165, 0.7293],
        [5.8802, 3.4843, 0.7048]], grad_fn=<AddmmBackward0>)
Output shape: torch.Size([3, 3])



In [125]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
print(x.dtype)
print(f'Mean: {x.type(torch.float32).mean()}')
print(f'Sum: {x.sum()}')

Minimum: 0
Maximum: 90
torch.int64
Mean: 45.0
Sum: 450


In [136]:
tensor = torch.arange(10, 100, 10)
print(f'Tensor: {tensor}\n')

print(f'Index there max value occurs {tensor.argmax()}')
print(f'Index there min value occurs {tensor.argmin()}')

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

Index there max value occurs 8
Index there min value occurs 0


In [138]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [139]:
tensor_float_16 = tensor.type(torch.float16)
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [141]:
tensor_int_8 = tensor.type(torch.int8)
tensor_int_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [142]:
import torch

In [144]:
x = torch.arange(1, 8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [147]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [149]:
z = x.view(1, 7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [150]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [152]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]])

In [156]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous tensor shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nSqueezed tensor: {x_squeezed}')
print(f'Squeezed tensor shape: {x_squeezed.shape}')

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
Previous tensor shape: torch.Size([1, 7])

Squeezed tensor: tensor([5, 2, 3, 4, 5, 6, 7])
Squeezed tensor shape: torch.Size([7])


In [159]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)

print(f'Previous shape {x_original.shape}')
print(f'New shape {x_permuted.shape}')

Previous shape torch.Size([224, 224, 3])
New shape torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [168]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [169]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [171]:
x[:, 0]

tensor([[1, 2, 3]])

In [172]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [178]:
x[:, 1, 1]

tensor([5])

In [179]:
x[0, 0, :]

tensor([1, 2, 3])

In [181]:
import torch
import numpy as np

array = np.array([1.0, 8.0])
tensor = torch.from_numpy(array)
tensor, array

(tensor([1., 8.], dtype=torch.float64), array([1., 8.]))

In [183]:
array = array + 1
array

array([ 3., 10.])

In [184]:
array, tensor

(array([ 3., 10.]), tensor([1., 8.], dtype=torch.float64))

In [185]:
tensor = torch.ones(7)
numpay_tensor = tensor.numpy()
tensor, numpay_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [186]:
tensor = tensor + 1
tensor, numpay_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [188]:
import torch

random_tensor_A = torch.rand(size=(3, 4))
random_tensor_B = torch.rand(size=(3, 4))

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2760, 0.3443, 0.2907, 0.2524],
        [0.3103, 0.1673, 0.8201, 0.9205],
        [0.2719, 0.2012, 0.1478, 0.3702]])

Tensor B:
tensor([[0.1441, 0.1284, 0.2582, 0.7732],
        [0.1060, 0.6737, 0.3027, 0.9716],
        [0.3592, 0.6261, 0.9557, 0.0057]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [191]:
import torch
import random

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(size=(3, 4))

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(size=(3, 4))

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [192]:
import torch
torch.cuda.is_available()

True

In [193]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [194]:
torch.cuda.device_count()

1

In [195]:
some_tensor = some_tensor.to(device)

In [197]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [198]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [199]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [200]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Exercises

In [201]:
# 2
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [205]:
tensor_A = torch.randn(size=(1, 7))
tensor_B = torch.randn(size=(1, 7))

result = torch.matmul(tensor_A, tensor_B.T)
result

tensor([[-0.0553]])

# 3



In [208]:
torch.manual_seed(42)

random_tensor = torch.randn(1, 7)
random_tensor

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082]])

In [213]:
torch.manual_seed(42)

tensor_A = torch.randn(size=(1, 7))

torch.manual_seed(42)
tensor_B = torch.randn(size=(1, 7))

torch.manual_seed(42)
result = torch.matmul(tensor_A, tensor_B.T)
result

tensor([[6.4097]])

# 6

In [222]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(1234)

random_tensor_A = torch.rand(size=(3, 4), device=device)
random_tensor_B = torch.rand(size=(3, 4), device=device)

print(random_tensor_A, random_tensor_B)

tensor([[0.1272, 0.8167, 0.5440, 0.6601],
        [0.2721, 0.9737, 0.3903, 0.3394],
        [0.5451, 0.7312, 0.3864, 0.5959]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255, 0.1114],
        [0.6812, 0.3608, 0.1715, 0.1965],
        [0.8400, 0.0438, 0.3011, 0.0285]], device='cuda:0')


In [223]:
result = torch.matmul(random_tensor_A, random_tensor_B.T)
print(f"random_tensor_A shape: {random_tensor_A.shape}")
print(f"random_tensor_B.T shape: {random_tensor_B.T.shape}")
print(f"Result shape: {result.shape}")
print(f"\nMatrix multiplication result:\n{result}")


random_tensor_A shape: torch.Size([3, 4])
random_tensor_B.T shape: torch.Size([4, 3])
Result shape: torch.Size([3, 3])

Matrix multiplication result:
tensor([[0.3522, 0.6043, 0.3252],
        [0.3607, 0.6703, 0.3983],
        [0.5508, 0.8185, 0.6232]], device='cuda:0')


In [229]:
min_result = torch.min(result)
max_result = torch.max(result)

print('Max value: ', max_result)
print('Min value: ', min_result)

Max value:  tensor(0.8185, device='cuda:0')
Min value:  tensor(0.3252, device='cuda:0')


In [228]:
max_index_result = torch.argmax(result)
min_index_result = torch.argmin(result)

print('Max value: ', max_index_result)
print('Min value: ', min_index_result)

Max value:  tensor(7, device='cuda:0')
Min value:  tensor(2, device='cuda:0')


In [232]:
torch.manual_seed(7)

random_tensor = torch.rand(size=(1, 1, 1, 10))

squeezed_tensor = random_tensor.squeeze()

print('Original tensor', random_tensor)
print('Original tensor shape', random_tensor.shape)

print('Squeezed tensor', squeezed_tensor)
print('Squeezed tensor shape', squeezed_tensor.shape)

Original tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original tensor shape torch.Size([1, 1, 1, 10])
Squeezed tensor tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed tensor shape torch.Size([10])
