# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [1]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars

In [2]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [3]:
!nvidia-smi

Sun Feb 23 18:31:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 31%   33C    P8             18W /  170W |    1819MiB /  12288MiB |     17%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([5])

In [10]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 2])

In [13]:
matrix[0]

tensor([1, 2])

In [14]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR.ndim

2

In [17]:
TENSOR.shape

torch.Size([3, 3])

In [18]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch

In [19]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.2025, 0.8976, 0.2543, 0.9758],
         [0.5864, 0.9552, 0.3095, 0.5980],
         [0.3928, 0.8879, 0.0302, 0.3999]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([1, 3, 4])

In [22]:
random_image_size_tensor = torch.rand(size=[224, 224, 3])
random_image_size_tensor

tensor([[[0.6662, 0.4506, 0.6835],
         [0.0094, 0.1577, 0.6242],
         [0.3631, 0.2121, 0.6972],
         ...,
         [0.2680, 0.5430, 0.6675],
         [0.4645, 0.3269, 0.4993],
         [0.0958, 0.4383, 0.1582]],

        [[0.3749, 0.1119, 0.3290],
         [0.4459, 0.7822, 0.5125],
         [0.6250, 0.1358, 0.4073],
         ...,
         [0.4835, 0.0237, 0.9406],
         [0.5436, 0.5729, 0.8371],
         [0.7333, 0.9130, 0.3999]],

        [[0.7842, 0.0596, 0.1819],
         [0.9195, 0.9985, 0.9546],
         [0.7513, 0.8252, 0.4881],
         ...,
         [0.1529, 0.0354, 0.3015],
         [0.1973, 0.3699, 0.7843],
         [0.7429, 0.3936, 0.0826]],

        ...,

        [[0.5198, 0.0464, 0.9156],
         [0.1668, 0.8021, 0.4634],
         [0.4668, 0.4806, 0.9739],
         ...,
         [0.1500, 0.9229, 0.4126],
         [0.2163, 0.2113, 0.4492],
         [0.8694, 0.0738, 0.8553]],

        [[0.1595, 0.9091, 0.4366],
         [0.4742, 0.7063, 0.5959],
         [0.

In [23]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# 22. Creating Tensors With Zeros and Ones in PyTorch

In [24]:
torch.rand(3, 3)

tensor([[0.1593, 0.3634, 0.7035],
        [0.6055, 0.6287, 0.2357],
        [0.7448, 0.6357, 0.0643]])

In [25]:
zeros = torch.zeros(3, 3)

In [26]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

# 23. Creating a Tensor Range and Tensors Like Other Tensors

In [29]:
one_to_ten = torch.arange(0, 11, 1)

In [30]:
torch.arange(start=0, end=100, step=3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 24. Dealing With Tensor Data Types

In [32]:
float_32_tensor = torch.tensor(
    [1, 2, 3],
    dtype=torch.float16,
    device="cuda",
    requires_grad=False
)
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [33]:
float_32_tensor.dtype

torch.float16

In [34]:
float_32_tensor.device

device(type='cuda', index=0)

In [35]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

# 25. Getting Tensor Attributes

In [36]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)

In [37]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

In [38]:
# int_32_tensor * float_32_tensor # Error

In [39]:
int_32_tensor.dtype

torch.int32

In [40]:
float_32_tensor.device

device(type='cuda', index=0)

In [41]:
float_32_tensor.requires_grad

False

In [42]:
float_32_tensor.shape

torch.Size([3])

In [43]:
float_32_tensor.size()

torch.Size([3])

# 26. Manipulating Tensors (Tensor Operations)

In [44]:
float_32_tensor.device

device(type='cuda', index=0)

In [45]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
tensor = tensor * 10

In [47]:
tensor - 15

tensor([-5,  5, 15])

In [48]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [49]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [50]:
torch.div(tensor, 10)

tensor([1., 2., 3.])

In [51]:
torch.sub(tensor, 10)

tensor([ 0, 10, 20])

# 27. Matrix Multiplication (Part 1)

In [56]:
tensor

tensor([10, 20, 30])

In [52]:
tensor * tensor

tensor([100, 400, 900])

In [53]:
print(tensor, '*', tensor)
print(f'PyTorch Multiplication: {torch.mul(tensor, tensor)}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
PyTorch Multiplication: tensor([100, 400, 900])


In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(1400)

In [55]:
tensor @ tensor

tensor(1400)

In [58]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: total: 0 ns
Wall time: 1.51 ms


# 28. Matrix Multiplication (Part 2): The Two Main Rules of Matrix Multiplication

In [60]:
tensor @ tensor

tensor(1400)

In [62]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [65]:
torch.rand(3, 10) @ torch.rand(10, 3)

tensor([[1.6636, 1.5817, 1.9194],
        [2.1744, 1.5198, 1.3695],
        [3.1107, 2.7960, 2.8984]])

# 29. Matrix Multiplication (Part 3): Dealing With Tensor Shape Errors

In [66]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [75]:
# torch.matmul(tensor_A, tensor_B) # Error

In [68]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [72]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [71]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [74]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [78]:
print(f" Original shapes: tensor A {tensor_A.shape}, tensor B = {tensor_B.shape}")
print(f'New shape: {torch.matmul(tensor_A, tensor_B.T).shape}')
print(f'Multiplication: {torch.matmul(tensor_A, tensor_B.T)}')
print(f'Output \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

 Original shapes: tensor A torch.Size([3, 2]), tensor B = torch.Size([3, 2])
New shape: torch.Size([3, 3])
Multiplication: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


# 30. Finding the Min Max Mean and Sum of Tensors (Tensor Aggregation)

In [79]:
x = torch.arange(0, 100, 10)

In [80]:
torch.sum(x)

tensor(450)

In [81]:
torch.min(x)

tensor(0)

In [82]:
torch.max(x)

tensor(90)

In [88]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [89]:
x.type(torch.float32).mean()

tensor(45.)

In [91]:
torch.sum(x), torch.min(x), torch.max(x), torch.mean(x, dtype=torch.float32)

(tensor(450), tensor(0), tensor(90), tensor(45.))

In [92]:
torch.argmax(x)

tensor(9)

In [93]:
torch.argmin(x)

tensor(0)

# 31. Finding The Positional Min and Max of Tensors