# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [1]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars
from torch.xpu import device

In [2]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [3]:
!nvidia-smi

Sun Jun 15 18:08:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.28                 Driver Version: 576.28         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 31%   39C    P3             28W /  170W |    4016MiB /  12288MiB |     14%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([5])

In [10]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 2])

In [13]:
matrix[0]

tensor([1, 2])

In [14]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR.ndim

2

In [17]:
TENSOR.shape

torch.Size([3, 3])

In [18]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch

In [19]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.0434, 0.6193, 0.7912, 0.5646],
         [0.3057, 0.0058, 0.5001, 0.6288],
         [0.8814, 0.0974, 0.2911, 0.6064]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([1, 3, 4])

In [22]:
random_image_size_tensor = torch.rand(size=[224, 224, 3])
random_image_size_tensor

tensor([[[0.4567, 0.3521, 0.7320],
         [0.9590, 0.3137, 0.0556],
         [0.0160, 0.2962, 0.8948],
         ...,
         [0.3140, 0.9291, 0.3131],
         [0.2114, 0.9666, 0.7266],
         [0.2647, 0.9337, 0.4586]],

        [[0.6824, 0.4239, 0.1193],
         [0.4668, 0.0043, 0.1346],
         [0.9815, 0.1558, 0.7159],
         ...,
         [0.0997, 0.8038, 0.6781],
         [0.4679, 0.0688, 0.5912],
         [0.8096, 0.9343, 0.0406]],

        [[0.8684, 0.2095, 0.7308],
         [0.1885, 0.6690, 0.3113],
         [0.1845, 0.1987, 0.5165],
         ...,
         [0.9585, 0.8347, 0.9442],
         [0.3080, 0.6049, 0.8688],
         [0.0541, 0.9018, 0.3828]],

        ...,

        [[0.7467, 0.0114, 0.8860],
         [0.5147, 0.8736, 0.2423],
         [0.0884, 0.2206, 0.7522],
         ...,
         [0.1787, 0.3175, 0.9536],
         [0.4142, 0.4385, 0.4721],
         [0.0771, 0.7163, 0.0797]],

        [[0.8864, 0.3333, 0.9290],
         [0.2662, 0.5218, 0.2848],
         [0.

In [23]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# 22. Creating Tensors With Zeros and Ones in PyTorch

In [24]:
torch.rand(3, 3)

tensor([[0.2888, 0.7766, 0.6062],
        [0.0600, 0.1011, 0.2956],
        [0.3800, 0.7027, 0.0608]])

In [25]:
zeros = torch.zeros(3, 3)

In [26]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

# 23. Creating a Tensor Range and Tensors Like Other Tensors

In [29]:
one_to_ten = torch.arange(0, 11, 1)

In [30]:
torch.arange(start=0, end=100, step=3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 24. Dealing With Tensor Data Types

In [32]:
float_32_tensor = torch.tensor(
    [1, 2, 3],
    dtype=torch.float16,
    device="cuda",
    requires_grad=False
)
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [33]:
float_32_tensor.dtype

torch.float16

In [34]:
float_32_tensor.device

device(type='cuda', index=0)

In [35]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

# 25. Getting Tensor Attributes

In [36]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)

In [37]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

In [38]:
# int_32_tensor * float_32_tensor # Error

In [39]:
int_32_tensor.dtype

torch.int32

In [40]:
float_32_tensor.device

device(type='cuda', index=0)

In [41]:
float_32_tensor.requires_grad

False

In [42]:
float_32_tensor.shape

torch.Size([3])

In [43]:
float_32_tensor.size()

torch.Size([3])

# 26. Manipulating Tensors (Tensor Operations)

In [44]:
float_32_tensor.device

device(type='cuda', index=0)

In [45]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
tensor = tensor * 10

In [47]:
tensor - 15

tensor([-5,  5, 15])

In [48]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [49]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [50]:
torch.div(tensor, 10)

tensor([1., 2., 3.])

In [51]:
torch.sub(tensor, 10)

tensor([ 0, 10, 20])

# 27. Matrix Multiplication (Part 1)

In [52]:
tensor

tensor([10, 20, 30])

In [53]:
tensor * tensor

tensor([100, 400, 900])

In [54]:
print(tensor, '*', tensor)
print(f'PyTorch Multiplication: {torch.mul(tensor, tensor)}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
PyTorch Multiplication: tensor([100, 400, 900])


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 6.71 ms


tensor(1400)

In [56]:
tensor @ tensor

tensor(1400)

In [57]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: total: 0 ns
Wall time: 1e+03 μs


# 28. Matrix Multiplication (Part 2): The Two Main Rules of Matrix Multiplication

In [58]:
tensor @ tensor

tensor(1400)

In [59]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [60]:
torch.rand(3, 10) @ torch.rand(10, 3)

tensor([[1.9473, 1.5382, 1.6783],
        [2.7991, 2.9063, 2.3772],
        [3.0163, 2.6171, 2.5665]])

# 29. Matrix Multiplication (Part 3): Dealing With Tensor Shape Errors

In [61]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [62]:
# torch.matmul(tensor_A, tensor_B) # Error

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [64]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [65]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [66]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [67]:
print(f" Original shapes: tensor A {tensor_A.shape}, tensor B = {tensor_B.shape}")
print(f'New shape: {torch.matmul(tensor_A, tensor_B.T).shape}')
print(f'Multiplication: {torch.matmul(tensor_A, tensor_B.T)}')
print(f'Output \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

 Original shapes: tensor A torch.Size([3, 2]), tensor B = torch.Size([3, 2])
New shape: torch.Size([3, 3])
Multiplication: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


# 30. Finding the Min Max Mean and Sum of Tensors (Tensor Aggregation)

In [68]:
x = torch.arange(0, 100, 10)

In [69]:
torch.sum(x)

tensor(450)

In [70]:
torch.min(x)

tensor(0)

In [71]:
torch.max(x)

tensor(90)

In [72]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [73]:
x.type(torch.float32).mean()

tensor(45.)

In [74]:
torch.sum(x), torch.min(x), torch.max(x), torch.mean(x, dtype=torch.float32)

(tensor(450), tensor(0), tensor(90), tensor(45.))

In [75]:
torch.argmax(x)

tensor(9)

In [76]:
torch.argmin(x)

tensor(0)

# 31. Finding The Positional Min and Max of Tensors

In [77]:
x = torch.arange(1, 101, 10)

In [78]:
x.argmax()

tensor(9)

In [79]:
x.argmin()

tensor(0)

# 32. Reshaping, Viewing and Stacking Tensors

In [80]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [81]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [82]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# 33. Squeezing, Unsqueezing and Permuting Tensors

In [85]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [86]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [87]:
print(f"Previous tensor: {x_reshaped}")
print(f'Previous shape: {x_reshaped.squeeze().shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [88]:
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.unsqueeze(dim=0).shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [89]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # color channel, width, height

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# 34. Selecting Data From Tensors (Indexing)

In [90]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [91]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [92]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [93]:
x[0][0]

tensor([1, 2, 3])

In [94]:
x[0][0][0]

tensor(1)

In [95]:
x[0][0][1]

tensor(2)

In [96]:
x[0][2][2]

tensor(9)

In [97]:
x[:,0]

tensor([[1, 2, 3]])

In [98]:
x[:,:,1]

tensor([[2, 5, 8]])

In [99]:
x[:,1 , 1]

tensor([5])

In [100]:
x[0, 0, :]

tensor([1, 2, 3])

In [101]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [102]:
x[0, 2, 2]

tensor(9)

# 35. PyTorch Tensors and NumPy

In [103]:
import numpy as np

In [104]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [105]:
array += 1

In [106]:
array

array([2., 3., 4., 5., 6., 7., 8.])

In [107]:
tensor = torch.ones(7)

In [108]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [109]:
tensor += 1
tensor, numpy_tensor
# from transformers import pipeline
# pipe = pipeline("text-generation", model="deepseek-ai/DeepSeek-R1")


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

# 36. PyTorch Reproducibility (Taking the Random Out of Random)

In [110]:
import  torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9469, 0.6224, 0.4303, 0.7212],
        [0.7823, 0.1082, 0.1284, 0.5069],
        [0.0516, 0.7226, 0.4199, 0.8681]])
tensor([[0.0524, 0.0960, 0.1642, 0.9089],
        [0.1069, 0.8321, 0.6211, 0.0489],
        [0.1726, 0.6414, 0.2929, 0.9550]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
import  torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [112]:
import  torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# 37. Different Ways of Accessing a GPU in PyTorch

In [113]:
import torch

torch.cuda.is_available()

True

In [116]:
!nvidia-smi

Sun Jun 15 18:09:32 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.28                 Driver Version: 576.28         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 32%   39C    P3             28W /  170W |    4137MiB /  12288MiB |     14%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [117]:
device = 'cuda'  if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [119]:
# count GPU

torch.cuda.device_count()

1

# 38. Setting up Device-Agnostic Code and Putting Tensors On and Off the GPU

In [124]:
tensor = torch.tensor([1, 2, 3, 4, 5], device='cpu')

print(tensor, tensor.device)

tensor([1, 2, 3, 4, 5]) cpu


In [125]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [128]:
# tensor_on_gpu.numpy() # Can't convert cuda:0 device type tensor to numpy

In [129]:
tensor_on_cpu = tensor.to('cpu')
tensor_on_cpu.numpy()

array([1, 2, 3, 4, 5])

# 39. PyTorch Fundamentals: Exercises and Extra-Curriculum