# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [2]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars

In [3]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [4]:
!nvidia-smi

Mon Feb 24 18:03:59 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 31%   34C    P8             18W /  170W |    1571MiB /  12288MiB |     41%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([5])

In [11]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([3, 2])

In [14]:
matrix[0]

tensor([1, 2])

In [15]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR.ndim

2

In [18]:
TENSOR.shape

torch.Size([3, 3])

In [19]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch

In [20]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.2686, 0.3423, 0.8028, 0.7728],
         [0.3126, 0.2427, 0.4575, 0.8025],
         [0.3710, 0.6811, 0.5514, 0.7917]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([1, 3, 4])

In [23]:
random_image_size_tensor = torch.rand(size=[224, 224, 3])
random_image_size_tensor

tensor([[[0.5427, 0.1758, 0.9573],
         [0.9308, 0.0666, 0.5325],
         [0.1298, 0.7220, 0.6909],
         ...,
         [0.1939, 0.9838, 0.9071],
         [0.5697, 0.4987, 0.4535],
         [0.0673, 0.3426, 0.7582]],

        [[0.2545, 0.6714, 0.6464],
         [0.3798, 0.5967, 0.2203],
         [0.3908, 0.6226, 0.7511],
         ...,
         [0.0235, 0.4574, 0.7567],
         [0.0637, 0.2822, 0.6859],
         [0.7270, 0.5717, 0.6755]],

        [[0.5384, 0.2138, 0.9306],
         [0.1216, 0.7293, 0.3248],
         [0.9978, 0.8053, 0.7666],
         ...,
         [0.5301, 0.5395, 0.7194],
         [0.0248, 0.7474, 0.7312],
         [0.8559, 0.3436, 0.3205]],

        ...,

        [[0.4610, 0.6797, 0.4978],
         [0.3268, 0.7235, 0.5867],
         [0.4414, 0.8221, 0.7673],
         ...,
         [0.7900, 0.2857, 0.2713],
         [0.2649, 0.4050, 0.0798],
         [0.9599, 0.4578, 0.2708]],

        [[0.8086, 0.1348, 0.5876],
         [0.2495, 0.9909, 0.7366],
         [0.

In [24]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# 22. Creating Tensors With Zeros and Ones in PyTorch

In [25]:
torch.rand(3, 3)

tensor([[0.3589, 0.7423, 0.9448],
        [0.0085, 0.2653, 0.6132],
        [0.6288, 0.2218, 0.8616]])

In [26]:
zeros = torch.zeros(3, 3)

In [27]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

# 23. Creating a Tensor Range and Tensors Like Other Tensors

In [30]:
one_to_ten = torch.arange(0, 11, 1)

In [31]:
torch.arange(start=0, end=100, step=3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 24. Dealing With Tensor Data Types

In [33]:
float_32_tensor = torch.tensor(
    [1, 2, 3],
    dtype=torch.float16,
    device="cuda",
    requires_grad=False
)
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [34]:
float_32_tensor.dtype

torch.float16

In [35]:
float_32_tensor.device

device(type='cuda', index=0)

In [36]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

# 25. Getting Tensor Attributes

In [37]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)

In [38]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

In [39]:
# int_32_tensor * float_32_tensor # Error

In [40]:
int_32_tensor.dtype

torch.int32

In [41]:
float_32_tensor.device

device(type='cuda', index=0)

In [42]:
float_32_tensor.requires_grad

False

In [43]:
float_32_tensor.shape

torch.Size([3])

In [44]:
float_32_tensor.size()

torch.Size([3])

# 26. Manipulating Tensors (Tensor Operations)

In [45]:
float_32_tensor.device

device(type='cuda', index=0)

In [46]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
tensor = tensor * 10

In [48]:
tensor - 15

tensor([-5,  5, 15])

In [49]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [50]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [51]:
torch.div(tensor, 10)

tensor([1., 2., 3.])

In [52]:
torch.sub(tensor, 10)

tensor([ 0, 10, 20])

# 27. Matrix Multiplication (Part 1)

In [53]:
tensor

tensor([10, 20, 30])

In [54]:
tensor * tensor

tensor([100, 400, 900])

In [55]:
print(tensor, '*', tensor)
print(f'PyTorch Multiplication: {torch.mul(tensor, tensor)}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
PyTorch Multiplication: tensor([100, 400, 900])


In [56]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 6.81 ms


tensor(1400)

In [57]:
tensor @ tensor

tensor(1400)

In [58]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: total: 31.2 ms
Wall time: 1 ms


# 28. Matrix Multiplication (Part 2): The Two Main Rules of Matrix Multiplication

In [59]:
tensor @ tensor

tensor(1400)

In [60]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [61]:
torch.rand(3, 10) @ torch.rand(10, 3)

tensor([[2.3580, 1.8498, 2.0864],
        [2.5338, 2.3815, 2.7208],
        [3.2118, 2.9353, 2.2817]])

# 29. Matrix Multiplication (Part 3): Dealing With Tensor Shape Errors

In [62]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [63]:
# torch.matmul(tensor_A, tensor_B) # Error

In [64]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [65]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [66]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [67]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [68]:
print(f" Original shapes: tensor A {tensor_A.shape}, tensor B = {tensor_B.shape}")
print(f'New shape: {torch.matmul(tensor_A, tensor_B.T).shape}')
print(f'Multiplication: {torch.matmul(tensor_A, tensor_B.T)}')
print(f'Output \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

 Original shapes: tensor A torch.Size([3, 2]), tensor B = torch.Size([3, 2])
New shape: torch.Size([3, 3])
Multiplication: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


# 30. Finding the Min Max Mean and Sum of Tensors (Tensor Aggregation)

In [69]:
x = torch.arange(0, 100, 10)

In [70]:
torch.sum(x)

tensor(450)

In [71]:
torch.min(x)

tensor(0)

In [72]:
torch.max(x)

tensor(90)

In [73]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [74]:
x.type(torch.float32).mean()

tensor(45.)

In [75]:
torch.sum(x), torch.min(x), torch.max(x), torch.mean(x, dtype=torch.float32)

(tensor(450), tensor(0), tensor(90), tensor(45.))

In [76]:
torch.argmax(x)

tensor(9)

In [77]:
torch.argmin(x)

tensor(0)

# 31. Finding The Positional Min and Max of Tensors

In [78]:
x = torch.arange(1, 101, 10)

In [79]:
x.argmax()

tensor(9)

In [80]:
x.argmin()

tensor(0)

# 32. Reshaping, Viewing and Stacking Tensors

In [81]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [89]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [93]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [94]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [102]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# 33. Squeezing, Unsqueezing and Permuting Tensors

In [103]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [105]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [107]:
print(f"Previous tensor: {x_reshaped}")
print(f'Previous shape: {x_reshaped.squeeze().shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [110]:
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.unsqueeze(dim=0).shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [113]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # color channel, width, height

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# 34. Selecting Data From Tensors (Indexing)

In [114]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [118]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [120]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [124]:
x[0][0]

tensor([1, 2, 3])

In [125]:
x[0][0][0]

tensor(1)

In [126]:
x[0][0][1]

tensor(2)

In [132]:
x[0][2][2]

tensor(9)

In [133]:
x[:,0]

tensor([[1, 2, 3]])

In [134]:
x[:,:,1]

tensor([[2, 5, 8]])

In [136]:
x[:,1 , 1]

tensor([5])

In [137]:
x[0, 0, :]

tensor([1, 2, 3])

In [143]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [147]:
x[0, 2, 2]

tensor(9)

# 35. PyTorch Tensors and NumPy