# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [3]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars

In [4]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [5]:
!nvidia-smi

Sat Jun  7 21:41:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.28                 Driver Version: 576.28         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 32%   41C    P3             28W /  170W |    4090MiB /  12288MiB |     25%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [8]:
scaler.item()

7

In [9]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([5])

In [12]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([3, 2])

In [15]:
matrix[0]

tensor([1, 2])

In [16]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
TENSOR.ndim

2

In [19]:
TENSOR.shape

torch.Size([3, 3])

In [20]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch

In [21]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.8377, 0.2855, 0.4797, 0.5346],
         [0.3363, 0.6793, 0.5314, 0.4410],
         [0.7219, 0.1616, 0.0692, 0.2182]]])

In [22]:
random_tensor.ndim

3

In [23]:
random_tensor.shape

torch.Size([1, 3, 4])

In [24]:
random_image_size_tensor = torch.rand(size=[224, 224, 3])
random_image_size_tensor

tensor([[[0.6948, 0.4981, 0.0740],
         [0.4150, 0.1310, 0.4158],
         [0.9953, 0.6034, 0.2475],
         ...,
         [0.7982, 0.2693, 0.7865],
         [0.3187, 0.5796, 0.0287],
         [0.6960, 0.0933, 0.9480]],

        [[0.8325, 0.8245, 0.9106],
         [0.1090, 0.9750, 0.4523],
         [0.3408, 0.0075, 0.2157],
         ...,
         [0.0636, 0.8548, 0.6130],
         [0.3507, 0.0875, 0.3928],
         [0.7348, 0.1634, 0.2101]],

        [[0.5995, 0.3206, 0.4526],
         [0.4324, 0.4072, 0.2585],
         [0.1209, 0.2682, 0.6937],
         ...,
         [0.1709, 0.5448, 0.3848],
         [0.9393, 0.1196, 0.7099],
         [0.5045, 0.0260, 0.4164]],

        ...,

        [[0.6810, 0.2054, 0.4991],
         [0.7222, 0.9855, 0.2180],
         [0.9513, 0.4587, 0.2233],
         ...,
         [0.7631, 0.7954, 0.6717],
         [0.3846, 0.3885, 0.4428],
         [0.2481, 0.9655, 0.0320]],

        [[0.3049, 0.0026, 0.5701],
         [0.1357, 0.0153, 0.7345],
         [0.

In [25]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# 22. Creating Tensors With Zeros and Ones in PyTorch

In [26]:
torch.rand(3, 3)

tensor([[0.7853, 0.4264, 0.6487],
        [0.1201, 0.3763, 0.4405],
        [0.7125, 0.9320, 0.2796]])

In [27]:
zeros = torch.zeros(3, 3)

In [28]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

# 23. Creating a Tensor Range and Tensors Like Other Tensors

In [31]:
one_to_ten = torch.arange(0, 11, 1)

In [32]:
torch.arange(start=0, end=100, step=3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 24. Dealing With Tensor Data Types

In [34]:
float_32_tensor = torch.tensor(
    [1, 2, 3],
    dtype=torch.float16,
    device="cuda",
    requires_grad=False
)
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [35]:
float_32_tensor.dtype

torch.float16

In [36]:
float_32_tensor.device

device(type='cuda', index=0)

In [37]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

# 25. Getting Tensor Attributes

In [38]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float16)

In [39]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

In [40]:
# int_32_tensor * float_32_tensor # Error

In [41]:
int_32_tensor.dtype

torch.int32

In [42]:
float_32_tensor.device

device(type='cuda', index=0)

In [43]:
float_32_tensor.requires_grad

False

In [44]:
float_32_tensor.shape

torch.Size([3])

In [45]:
float_32_tensor.size()

torch.Size([3])

# 26. Manipulating Tensors (Tensor Operations)

In [46]:
float_32_tensor.device

device(type='cuda', index=0)

In [47]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [48]:
tensor = tensor * 10

In [49]:
tensor - 15

tensor([-5,  5, 15])

In [50]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [51]:
torch.add(tensor, 10)

tensor([20, 30, 40])

In [52]:
torch.div(tensor, 10)

tensor([1., 2., 3.])

In [53]:
torch.sub(tensor, 10)

tensor([ 0, 10, 20])

# 27. Matrix Multiplication (Part 1)

In [54]:
tensor

tensor([10, 20, 30])

In [55]:
tensor * tensor

tensor([100, 400, 900])

In [56]:
print(tensor, '*', tensor)
print(f'PyTorch Multiplication: {torch.mul(tensor, tensor)}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
PyTorch Multiplication: tensor([100, 400, 900])


In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 7 ms


tensor(1400)

In [58]:
tensor @ tensor

tensor(1400)

In [59]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: total: 0 ns
Wall time: 2 ms


# 28. Matrix Multiplication (Part 2): The Two Main Rules of Matrix Multiplication

In [60]:
tensor @ tensor

tensor(1400)

In [61]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [62]:
torch.rand(3, 10) @ torch.rand(10, 3)

tensor([[2.4555, 1.7322, 1.4061],
        [3.0244, 2.7937, 2.2205],
        [2.5640, 1.8745, 2.3019]])

# 29. Matrix Multiplication (Part 3): Dealing With Tensor Shape Errors

In [63]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [64]:
# torch.matmul(tensor_A, tensor_B) # Error

In [65]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [66]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [67]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [68]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [69]:
print(f" Original shapes: tensor A {tensor_A.shape}, tensor B = {tensor_B.shape}")
print(f'New shape: {torch.matmul(tensor_A, tensor_B.T).shape}')
print(f'Multiplication: {torch.matmul(tensor_A, tensor_B.T)}')
print(f'Output \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

 Original shapes: tensor A torch.Size([3, 2]), tensor B = torch.Size([3, 2])
New shape: torch.Size([3, 3])
Multiplication: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


# 30. Finding the Min Max Mean and Sum of Tensors (Tensor Aggregation)

In [70]:
x = torch.arange(0, 100, 10)

In [71]:
torch.sum(x)

tensor(450)

In [72]:
torch.min(x)

tensor(0)

In [73]:
torch.max(x)

tensor(90)

In [74]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [75]:
x.type(torch.float32).mean()

tensor(45.)

In [76]:
torch.sum(x), torch.min(x), torch.max(x), torch.mean(x, dtype=torch.float32)

(tensor(450), tensor(0), tensor(90), tensor(45.))

In [77]:
torch.argmax(x)

tensor(9)

In [78]:
torch.argmin(x)

tensor(0)

# 31. Finding The Positional Min and Max of Tensors

In [79]:
x = torch.arange(1, 101, 10)

In [80]:
x.argmax()

tensor(9)

In [81]:
x.argmin()

tensor(0)

# 32. Reshaping, Viewing and Stacking Tensors

In [82]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [84]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [85]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [86]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# 33. Squeezing, Unsqueezing and Permuting Tensors

In [87]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [88]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [89]:
print(f"Previous tensor: {x_reshaped}")
print(f'Previous shape: {x_reshaped.squeeze().shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [90]:
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.unsqueeze(dim=0).shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [91]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # color channel, width, height

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# 34. Selecting Data From Tensors (Indexing)

In [92]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [93]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [94]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
x[0][0]

tensor([1, 2, 3])

In [96]:
x[0][0][0]

tensor(1)

In [97]:
x[0][0][1]

tensor(2)

In [98]:
x[0][2][2]

tensor(9)

In [99]:
x[:,0]

tensor([[1, 2, 3]])

In [100]:
x[:,:,1]

tensor([[2, 5, 8]])

In [101]:
x[:,1 , 1]

tensor([5])

In [102]:
x[0, 0, :]

tensor([1, 2, 3])

In [103]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [104]:
x[0, 2, 2]

tensor(9)

# 35. PyTorch Tensors and NumPy

In [105]:
import numpy as np

In [106]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [107]:
array += 1

In [108]:
array

array([2., 3., 4., 5., 6., 7., 8.])

In [109]:
tensor = torch.ones(7)

In [110]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
tensor += 1
tensor, numpy_tensor
# from transformers import pipeline
# pipe = pipeline("text-generation", model="deepseek-ai/DeepSeek-R1")


ModuleNotFoundError: No module named 'transformers'

# 36. PyTorch Reproducibility (Taking the Random Out of Random)

In [114]:
import  torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4740, 0.5235, 0.0108, 0.5746],
        [0.4773, 0.1980, 0.7205, 0.8161],
        [0.3763, 0.9088, 0.3906, 0.9293]])
tensor([[0.4877, 0.4994, 0.4827, 0.6625],
        [0.5193, 0.1017, 0.9110, 0.0693],
        [0.2230, 0.5023, 0.5388, 0.6640]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [115]:
import  torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [116]:
import  torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
