# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [1]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars

In [2]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [3]:
!nvidia-smi

Fri Feb 21 23:02:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 31%   31C    P8             19W /  170W |    1547MiB /  12288MiB |     43%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [10]:
scaler.item()

7

In [11]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([5])

In [14]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [16]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([3, 2])

In [19]:
matrix[0]

tensor([1, 2])

In [20]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
TENSOR.ndim

2

In [24]:
TENSOR.shape

torch.Size([3, 3])

In [28]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch