# 8. Why Use Machine Learning or Deep Learning

# 9. The Number 1 Rule of Machine Learning and What Is Deep Learning Good For

# 10. Machine Learning vs. Deep Learning

# 11. Anatomy of Neural Networks

# 12. Different Types of Learning Paradigms

# 13. What Can Deep Learning Be Used For

# 14. What Is and Why PyTorch

# 15. What Are Tensors

# 16. What We Are Going To Cover With PyTorch

# 17. How To and How Not To Approach This Course

# 19. Getting Setup to Write PyTorch Code

In [1]:
import torch
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import plotly.express as px
import numpy as np
import hvplot.polars

In [2]:
print(torch.__version__)
print(f"CUDA available: {torch.cuda.is_available()}")

2.6.0+cu126
CUDA available: True


# 20. Introduction to PyTorch Tensors

In [3]:
!nvidia-smi

Sat Feb 22 11:39:54 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:2B:00.0  On |                  N/A |
| 31%   31C    P8             17W /  170W |    1371MiB /  12288MiB |     17%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([5])

In [10]:
# Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 2])

In [13]:
matrix[0]

tensor([1, 2])

In [14]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR.ndim

2

In [17]:
TENSOR.shape

torch.Size([3, 3])

In [18]:
TENSOR[0]

tensor([1, 2, 3])

# 21. Creating Random Tensors in PyTorch

In [28]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.0941, 0.3437, 0.6487, 0.2031],
         [0.0907, 0.3839, 0.3540, 0.8330],
         [0.7532, 0.7157, 0.0677, 0.6838]]])

In [29]:
random_tensor.ndim

3

In [30]:
random_tensor.shape

torch.Size([1, 3, 4])

In [34]:
random_image_size_tensor = torch.rand(size=[224, 224, 3])
random_image_size_tensor

tensor([[[0.8339, 0.5901, 0.9308],
         [0.7242, 0.2636, 0.4327],
         [0.4029, 0.4314, 0.5501],
         ...,
         [0.1823, 0.4373, 0.6490],
         [0.7347, 0.4745, 0.7405],
         [0.9317, 0.2123, 0.4987]],

        [[0.4700, 0.5907, 0.7174],
         [0.5537, 0.7981, 0.0681],
         [0.3600, 0.1609, 0.1506],
         ...,
         [0.7752, 0.8099, 0.6816],
         [0.3886, 0.7434, 0.4154],
         [0.9549, 0.7121, 0.0352]],

        [[0.7410, 0.2760, 0.4632],
         [0.1349, 0.0694, 0.4957],
         [0.9625, 0.3981, 0.3473],
         ...,
         [0.2844, 0.2400, 0.6337],
         [0.1315, 0.2265, 0.7435],
         [0.5849, 0.6693, 0.1447]],

        ...,

        [[0.5799, 0.7526, 0.4612],
         [0.5223, 0.4430, 0.7920],
         [0.3000, 0.2199, 0.5013],
         ...,
         [0.1991, 0.5373, 0.8245],
         [0.6524, 0.8177, 0.0756],
         [0.5912, 0.3692, 0.4633]],

        [[0.2719, 0.0504, 0.8509],
         [0.6542, 0.8607, 0.7991],
         [0.

In [35]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# 22. Creating Tensors With Zeros and Ones in PyTorch

In [36]:
torch.rand(3, 3)

tensor([[0.8662, 0.4159, 0.7804],
        [0.9175, 0.8130, 0.3982],
        [0.9287, 0.4645, 0.5622]])

In [38]:
zeros = torch.zeros(3, 3)

In [40]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

# 23. Creating a Tensor Range and Tensors Like Other Tensors